# Generated by Django 4.0.3 on 2022-05-30 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appshop', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop',
            name='isOpened',
            field=models.BooleanField(default=False),
        ),
    ]
