# Generated by Django 4.0.3 on 2022-05-31 10:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appshop', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shop',
            name='city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cities', to='appshop.city'),
        ),
        migrations.AlterField(
            model_name='shop',
            name='schedule',
            field=models.ManyToManyField(related_name='schedules', to='appshop.schedule', verbose_name='Расписание магазина'),
        ),
        migrations.AlterField(
            model_name='shop',
            name='street',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='streets', to='appshop.street'),
        ),
    ]
