# Generated by Django 4.0.3 on 2022-06-01 10:14

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appshop', '0002_alter_shop_city_alter_shop_schedule_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shop',
            name='schedule',
        ),
        migrations.AddField(
            model_name='shop',
            name='close_time',
            field=models.TimeField(default=datetime.time(18, 0)),
        ),
        migrations.AddField(
            model_name='shop',
            name='opening_time',
            field=models.TimeField(default=datetime.time(9, 0)),
        ),
        migrations.AlterField(
            model_name='shop',
            name='city',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cities', to='appshop.city'),
        ),
        migrations.AlterField(
            model_name='shop',
            name='street',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appshop.street'),
        ),
        migrations.DeleteModel(
            name='Schedule',
        ),
    ]
