# Generated by Django 4.0.3 on 2022-06-06 09:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appshop', '0003_remove_shop_schedule_shop_close_time_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shop',
            name='isOpened',
        ),
    ]
